### ISSUE TITLE
Issue: Unable to run the Jar due to database Issue

### ISSUE THREAD

**Issue by guttmann-avi** [andrijaradiv/EECS3311GroupProject#15]
Description

I was trying to run the project but was unable to due to data base issue. I have Java 19 installed and when I asked about needing a database of any kind was told it was handled by the program and that it is a local file. Unsure at this time what is needed to run the program as there is also no documentation explaining the type of database if any is needed.

Date Reported 
March 17 2023

Recommended fix
- updated documentation stating if and what kind of database needs to be installed on a computer

Severity:
Medium
![Database](https://user-images.githubusercontent.com/77285621/225914339-382459a2-5723-447f-a71c-7e33ca09a216.png)

**Comment by GabrielERincon** [comment]
Moved the db to the root folder to not rely on a directory which may not exist on the testing machine.
