### ISSUE TITLE
SuccessfulReturn condition 

### ISSUE THREAD

**Issue by Abdullah-Djama** [andrijaradiv/EECS3311GroupProject#17]
Description
SuccessfulReturn method in the  Return Class uses bad code style .

Date Reported 
March 17 2023

Code under review 

![Screenshot 2023-03-17 174433](https://user-images.githubusercontent.com/67915599/226059305-3b244535-c8ee-44bf-8696-0b81e4ea2425.jpg)

Issue 
The method of sucessfulReturn is using bad coding practices since this larger  project is in reorder for the code so that it can be useful in the future. The phrase break; is  legacy Java code and might even get deprecated it the future. 

Recommend Fix
Have the negation of the if condition statement  code as a part  for loop  condition  statement.

Severity 
Medium

**Comment by andrijaradiv** [comment]
This code works on the current version of java and does not plan to be implemented on newer version of java. Method currently works and gives proper result without error.
