### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by Abdullah-Djama** [andrijaradiv/EECS3311GroupProject#18]
Description

No enough test are being provided for the codebase.

Date Reported
March 17 2023

code under review
package clothing4you;

import org.junit.Test;

import javax.swing.*;
import java.sql.SQLException;
import java.util.ArrayList;

import static org.junit.Assert.assertEquals;

public class UserTest {
    @Test
    public void createNewUser() throws SQLException, ClassNotFoundException {
        String createTestTable = "CREATE TABLE IF NOT EXISTS test (" +
                "ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                "first_name TEXT," +
                "email TEXT," +
                "username TEXT," +
                "password TEXT" +
                ");";
        JDBC.createTable("test", createTestTable);

        String name = "John Doe";
        String email = "johnDoe@my.yorku.ca";
        String username = "JohnDoe";
        String password = "JohnDoe";
        UserManager.register(name, email, username, password, "test");
        ArrayList res = (ArrayList) JDBC.database("select first_name from test where username==\"" + username + "\";");
        assertEquals(res.get(0), name);
    }
}

Fix
Cover all aspects of code in test need full coverage 

severity
low

**Comment by andrijaradiv** [comment]
Large number of tests, testing the functionality of the classes have been added.
